version: "3.8"
services:
  rabbitmq:
    restart: unless-stopped
    image: arm32v7/rabbitmq:3.10.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /opt/volumes/rabbitmq/data:/var/lib/rabbitmq/
      - /opt/volumes/rabbitmq/log:/var/log/rabbitmq/
networks: {}
