version: "3.8"
services:
  mariadb:
    restart: unless-stopped
    image: linuxserver/mariadb:arm32v7-alpine-10.5.16-r0-ls63
    ports:
      - 33060:3306
    volumes:
      - /opt/volumes/mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r00t!
      - MYSQL_DATABASE=rpi
      - MYSQL_USER=rpi
      - MYSQL_PASSWORD=rpi
  adminer:
    restart: unless-stopped
    image: adminer:latest
    ports:
      - 7777:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
networks: {}